### ISSUE TITLE
执行完之后fly.io没有内容

### ISSUE THREAD

**Issue by IonRh** [lyj0309/nezha-fly#1]
大佬，步骤可否写的详细点，环境变量配好之后，执行action后fly.io没有内容

**Comment by lyj0309** [comment]
第一次部署需要把`action`中的`if: ${{ env.new_release == 'yes'  }}`注释掉，部署成功之后再注回来

**Comment by IonRh** [comment]
> 第一次部署需要把`action`中的`if: ${{ env.new_release == 'yes' }}`注释掉，部署成功之后再注回来
感谢大佬，成功了
